# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chess.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chess.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hess.proto\x12\x05\x63hess\"\x92\x01\n\x13ValidateMoveRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x11\n\tplayer_id\x18\x02 \x01(\t\x12\x16\n\x0epiece_position\x18\x03 \x01(\t\x12\x17\n\x0ftarget_position\x18\x04 \x01(\t\x12\x11\n\tmove_type\x18\x05 \x01(\t\x12\x13\n\x0b\x62oard_state\x18\x06 \x01(\t\"\x91\x01\n\x14ValidateMoveResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x11\n\tmove_type\x18\x02 \x01(\t\x12\x13\n\x0b\x63heck_state\x18\x03 \x01(\x08\x12\x11\n\tcheckmate\x18\x04 \x01(\x08\x12\x15\n\rupdated_board\x18\x05 \x01(\t\x12\x15\n\rerror_message\x18\x06 \x01(\t2X\n\rMoveValidator\x12G\n\x0cValidateMove\x12\x1a.chess.ValidateMoveRequest\x1a\x1b.chess.ValidateMoveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chess_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATEMOVEREQUEST']._serialized_start=23
  _globals['_VALIDATEMOVEREQUEST']._serialized_end=169
  _globals['_VALIDATEMOVERESPONSE']._serialized_start=172
  _globals['_VALIDATEMOVERESPONSE']._serialized_end=317
  _globals['_MOVEVALIDATOR']._serialized_start=319
  _globals['_MOVEVALIDATOR']._serialized_end=407
# @@protoc_insertion_point(module_scope)
